language: cpp
os: linux
compiler: gcc
sudo: required
dist: trusty

# Add encrypted API key
env:
  global:
    - secure: D8yS8J76Kwq0V3OUIRfvNdKVvJGnLwJsm0Pf34wwfuz7ilLRcmv24pViIc7VcfDyLj5COAM60Ri53IfAeTfFD5xVdCgLjZJVm3BVv76V54rMmI/X3YJommuIBMB36wh0ETC/Htr71niSS5Nsp1Nw/5YV4KtQGK7ClUEsMZJgjn+vTfB4KKAwy87jcOzZMIvQUaQJCwhgm1YjBhcv7Gv4Bk/3gvnHN9bLc2ubC66Cg93MNXCnctwVliTtMAGOisOI2t0zGPPoBZioBDcfnF3fd1zgfqH2VQZsuOrWrdoyXXuYPzFCfYrSOnI2JSqDKeDqxzKlrin/8nKQRPuFesrSCpsXCT6VktVtc7FRt56AqNxD0JDBcNWDhCXafh9EwCwKqVIuhFV7hvDM6C3EvaN92f4arBf/+7B+VujuavQhNn4cwcT6R+Btpb0QtymJcZFADwU/iXj3d+rR8IOVpgVJ9yZ/RSiutwNMlg1lcgH/Lrj9ECB3mA1EgSq5PYSm5Z+CtIpuVVGqeebvq/DOIUow9qD1/UTTvhb6c7HSYYE5mMwEQhr3sE1HtB/YvZNFyQ2E5WO2SdxLVtnKmB1AOqSP+L/ijIQbahJxUB8VupDdb4962V32jVhphpSJv3ZKThDPu66ZHmXnjSDhHS42N4KF3yDUpHQBt43FUaS0t2Ktjgc=

addons:
  apt:
    sources:
    # Add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    packages:
    # Install toolchains
    - gcc-6
    - g++-6

before_install:
  # Get the latest version of the Geometrize library submodule, and push it to the remote (if necessary)
  - chmod +x ./travis_update_geometrize_submodule.sh
  - ./travis_update_geometrize_submodule.sh

install:
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - sudo apt-get install -y qt5-default qttools5-dev-tools

# Build the program to fuzz
script:
  - qmake geometrize-lib-fuzzing.pro
  - make